version: '3.6'

services:
  imageur:
    image: winwin2011/imageur:0.1.0
    container_name: imageur
    restart: unless-stopped
    ports:
      -3000:3000
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - ACCESS_KEY_SECRET=${ACCESS_KEY_SECRET}
      - ARN=${ARN}
      - REGION=${REGION}
      - BUCKET=${BUCKET}
